# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SamaCli < Formula
  desc "This is the Sama CLI, a command-line tool for using the Sama Data API."
  homepage "https://github.com/Samasource/homebrew-formulas"
  version "1.5.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/Samasource/sama-cli/releases/download/v1.5.0/sama-cli_1.5.0_darwin_x86_64.tar.gz"
      sha256 "58d235846fdaaf6a6b3f94305c7fde51754dc4e6979f66712b28964812cb2767"
    end
    if Hardware::CPU.arm?
      url "http://github.com/Samasource/sama-cli/releases/download/v1.5.0/sama-cli_1.5.0_darwin_arm64.tar.gz"
      sha256 "8df20e6b05afc1654e228a1c6c420a818b62c5cceed5f92c6015ee2b242999f3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/Samasource/sama-cli/releases/download/v1.5.0/sama-cli_1.5.0_linux_x86_64.tar.gz"
      sha256 "a4b22a347dfc313a61794e12d55ad2862708dfbc0b085941a6f71a293c90b176"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/Samasource/sama-cli/releases/download/v1.5.0/sama-cli_1.5.0_linux_arm64.tar.gz"
      sha256 "04de8fa8fc8141b7f0471801903c796af0172c6c5c708242ce0524dfe749fbf4"
    end
  end

  def install
    bin.install "sama"
  end
end
